# GitHub Actions workflow to run Robot Framework acceptance tests and upload logs
name: Run Robot Framework Tests

# Trigger workflow on pushes and PRs to master, except when only README.md changes
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  run_tests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.10 (with pip cache enabled)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # 3. Install the LEDSA package (and its dependencies) from the repository root
      - name: Install LEDSA package and dependencies
        run: pip install .

      # 4. Create a directory where Robot Framework will place its reports (HTML, XML, etc.)
      - name: Create folder for reports
        run: mkdir reports

      # 5. Execute Robot Framework acceptance tests located in ledsa/tests/AcceptanceTests
      #    The --outputdir option tells Robot where to store its output files.
      - name: Run Robot Framework Tests
        run: |
          robot \
          --outputdir reports \
          ledsa/tests/AcceptanceTests

      # 6. Always upload the test logs & reports as a GitHub Actions artifact so they can be inspected
      - name: Upload Robot Framework logs
        if: always()  # Run this step regardless of test success/failure
        uses: actions/upload-artifact@v3
        with:
          name: robot-framework-logs  # Artifact name in the Actions UI
          path: results/  # Directory (or file) to upload
